USE UNIVER;
GO
CREATE VIEW [опеондюбюрекх] AS
	SELECT TEACHER.TEACHER [йнд], 
		TEACHER.TEACHER_NAME [хлъ], 
		TEACHER.GENDER [онк], 
		TEACHER.PULPIT [йютедпю]
			FROM TEACHER;
GO
SELECT * FROM опеондюбюрекх;
GO
CREATE VIEW [йнк-бн йютедп] AS
	SELECT FACULTY.FACULTY_NAME, COUNT(*)[йнкбн]
			FROM FACULTY INNER JOIN PULPIT
				ON FACULTY.FACULTY = PULPIT.FACULTY
			GROUP BY FACULTY.FACULTY_NAME;
GO
SELECT * FROM [йнк-бн йютедп];
GO
CREATE VIEW [юсдхрнпхх](йнд, хлъ) AS
	SELECT AUDITORIUM.AUDITORIUM [йнд],
			AUDITORIUM.AUDITORIUM_NAME [хлъ]
				FROM AUDITORIUM
				WHERE AUDITORIUM.AUDITORIUM_TYPE LIKE 'кй%'
GO
/*INSERT юсдхрнпхх VALUES('121-1', '121-1');*/
SELECT * FROM юсдхрнпхх;
GO
CREATE VIEW [кейжхнммше юсдхрнпхх](йнд, рхо, хлъ) AS
	SELECT AUDITORIUM.AUDITORIUM [йнд],
			AUDITORIUM.AUDITORIUM_NAME [хлъ],
			AUDITORIUM.AUDITORIUM_TYPE [рхо]
				FROM AUDITORIUM
				WHERE AUDITORIUM.AUDITORIUM_TYPE LIKE 'кй%' WITH CHECK OPTION;
GO
/*INSERT [кейжхнммше юсдхрнпхх] VALUES('132-3', 'кй', '132-3');*/
SELECT * FROM [кейжхнммше юсдхрнпхх];
GO
CREATE VIEW [дхяжхокхмш] AS
	SELECT TOP 150 SUBJECT.SUBJECT [йнд],
			SUBJECT.SUBJECT_NAME [мюхлемнбюмхе],
			SUBJECT.PULPIT [йютедпю]
			FROM SUBJECT
			ORDER BY мюхлемнбюмхе ASC;
GO
SELECT * FROM дхяжхокхмш;
GO
ALTER VIEW [йнк-бн йютедп] WITH SCHEMABINDING AS
	SELECT FACULTY.FACULTY_NAME, COUNT(*)[йнкбн]
			FROM dbo.FACULTY INNER JOIN dbo.PULPIT
				ON FACULTY.FACULTY = PULPIT.FACULTY
			GROUP BY FACULTY.FACULTY_NAME;
GO
SELECT * FROM [йнк-бн йютедп];