USE UNIVER;
GO
/*CREATE PROCEDURE PSUBJECT
AS
BEGIN
	DECLARE @code int = (SELECT COUNT(*) FROM SUBJECT);
	SELECT * FROM SUBJECT;
	RETURN @code;
END;*/
/*CREATE TABLE #SUBJECT
(
CODE VARCHAR(10) PRIMARY KEY,
SUBJECT VARCHAR(30),
SUBJECT_NAME VARCHAR(30),
)*/
DECLARE @k int = 0, @p char(10) = '»—Ë“';
--INSERT #SUBJECT EXEC PSUBJECT @p = '»—Ë“';
--SELECT * FROM #SUBJECT;
PRINT 'ÍÓÎ-‚Ó ÒÚÓÍ ' + CAST(@k AS CHAR(4));
GO
/*CREATE PROCEDURE PAUDITORIUM_INSERT @a char(20), @n varchar(50), @c int = 0, @t char(10)
AS
BEGIN TRY
	INSERT INTO AUDITORIUM(AUDITORIUM, AUDITORIUM_NAME, AUDITORIUM_CAPACITY, AUDITORIUM_TYPE)
		VALUES (@a, @n, @c, @t)
		RETURN 1;
END TRY
BEGIN CATCH
	PRINT 'ERROR_NUMBER ' + CAST(ERROR_NUMBER() AS VARCHAR(6));
	PRINT 'ERROR_MESSAGE ' + ERROR_MESSAGE();
	RETURN -1;
END CATCH;*/
EXEC PAUDITORIUM_INSERT @a = '121-3', @n = 'À -¡', @c = 250, @t = 'À -¡';
GO
/*CREATE PROCEDURE SUBJECT_REPORT @p char(10)
AS
	DECLARE @r int = 0;
BEGIN TRY
	DECLARE @tv char(20), @t char(300) = '';
	DECLARE SUBJCURS CURSOR FOR
		SELECT SUBJECT.SUBJECT FROM SUBJECT WHERE PULPIT=@p;
		IF NOT EXISTS (SELECT SUBJECT FROM SUBJECT WHERE PULPIT=@p)
			RAISERROR('ERROR', 11, 1);
		ELSE
			OPEN SUBJCURS;
			FETCH SUBJCURS INTO @tv;
			PRINT 'ƒËÒˆËÔÎËÌ˚ Ì‡ Í‡ÙÂ‰Â';
			WHILE @@FETCH_STATUS = 0
			BEGIN
				SET @t = RTRIM(@tv) + ',' + @t;
				SET @r = @r + 1;
				FETCH SUBJCURS INTO @tv;
			END;
			PRINT @t;
			CLOSE SUBJCURS;
			RETURN @r;
END TRY
BEGIN CATCH
	PRINT 'Œÿ»¡ ¿ ¬ œ¿–¿Ã≈“–¿’';
	IF ERROR_PROCEDURE() IS NOT NULL
		PRINT 'œ–Œ÷≈ƒ”–¿: ' + ERROR_PROCEDURE();
	RETURN @R;
END CATCH;
DECLARE @r int = 0;
EXEC @r = SUBJECT_REPORT @p = '»—Ë“';
PRINT @r;*/
GO
CREATE PROCEDURE PAUDITORIUM_INSERTX @a char(20), @n varchar(50), @c int = 0, @t char(10), @tn VARCHAR(50)
AS DECLARE @rc INT = 0;
BEGIN
	SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
	BEGIN TRAN
		INSERT INTO AUDITORIUM_TYPE( AUDITORIUM_TYPE, AUDITORIUM_TYPENAME) VALUES(@t, @tn);
		EXEC @rc = PAUDITORIUM_INSERT @a = @a, @n = @n, @c = @c, @t = @t;
	COMMIT TRAN;
	RETURN @rc;
END;
SET @rc = 0;
EXEC @rc = PAUDITORIUM_INSERTX @a = '012-1',@n = 'À ',@c = 20,@t = 'À ', @tn =  'À≈ ÷»ŒÕÕ¿ﬂ';
PRINT CAST(@rc AS VARCHAR(4));
