use SHOP;

/* 1 Задание 
	Найти товары, которые заказывали сотрудники из офисов Восточного региона*/

SELECT ORDERS.CUST, ORDERS.PRODUCT FROM ORDERS
	INNER JOIN SALESREPS
	ON ORDERS.REP = SALESREPS.MANAGER
	INNER JOIN OFFICES
	ON SALESREPS.REP_OFFICE = OFFICES.OFFICE
		WHERE OFFICES.REGION LIKE '%Eastern%';
---

SELECT ORDERS.CUST, AVG(ORDERS.AMOUNT)[СР ЦЕНА] FROM ORDERS
INNER JOIN CUSTOMERS
ON ORDERS.CUST = CUSTOMERS.CUST_NUM
	WHERE ORDERS.AMOUNT > 600
	GROUP BY ORDERS.CUST;
