ALTER PLUGGABLE DATABASE TDV_PDB
  OPEN READ WRITE FORCE;

DROP TABLE T_RANGE;
DROP TABLE T_INTERVAL;
DROP TABLE T_LIST;
DROP TABLE T_HASH;

CREATE TABLE T_RANGE (
   ID NUMBER,
   NAME VARCHAR2(50),
   SALARY NUMBER)
   PARTITION BY RANGE (SALARY)
   (
      PARTITION p1 VALUES LESS THAN (5000),
      PARTITION p2 VALUES LESS THAN (10000),
      PARTITION p3 VALUES LESS THAN (15000),
      PARTITION p4 VALUES LESS THAN (MAXVALUE)
   );

CREATE TABLE T_INTERVAL (
   ID date,
   NAME VARCHAR2(50),
   SALARY NUMBER
)
   PARTITION BY RANGE(ID)
   INTERVAL (NUMTOYMINTERVAL(1, 'MONTH'))
   (
      PARTITION p1 VALUES LESS THAN (TO_DATE('14-APR-2023','DD-MON-YYYY'))
   );

CREATE TABLE T_HASH (
   ID NUMBER,
   NAME VARCHAR2(50),
   SALARY NUMBER,
   CONSTRAINT pk_t_hash PRIMARY KEY (ID))
   PARTITION BY HASH (NAME)
   PARTITIONS 4;

CREATE TABLE T_LIST (
   ID NUMBER,
   NAME VARCHAR2(50),
   SALARY NUMBER,
   CONSTRAINT pk_t_list PRIMARY KEY (ID))
   PARTITION BY LIST (NAME)
   (
      PARTITION p1 VALUES ('John', 'Michael'),
      PARTITION p2 VALUES ('Chris', 'Lena'),
      PARTITION p3 VALUES ('Sophie', 'Olivia'),
      PARTITION p4 VALUES (DEFAULT)
   );



SELECT COUNT(*) FROM T_RANGE PARTITION (P1);
SELECT COUNT(*) FROM T_RANGE PARTITION (P2);
SELECT COUNT(*) FROM T_RANGE PARTITION (P3);
SELECT COUNT(*) FROM T_RANGE PARTITION (P4);

SELECT COUNT(*) FROM T_INTERVAL PARTITION (P1);

SELECT COUNT(*) FROM T_HASH PARTITION (SYS_P348);
SELECT COUNT(*) FROM T_HASH PARTITION (SYS_P349);
SELECT COUNT(*) FROM T_HASH PARTITION (SYS_P350);
SELECT COUNT(*) FROM T_HASH PARTITION (SYS_P351);

SELECT COUNT(*) FROM T_LIST PARTITION (P1);
SELECT COUNT(*) FROM T_LIST PARTITION (P2);
SELECT COUNT(*) FROM T_LIST PARTITION (P3);
SELECT COUNT(*) FROM T_LIST PARTITION (P4);

-- Перемещение строк между секциями при изменении ключа секционирования
alter table T_RANGE enable row movement;
UPDATE T_RANGE SET SALARY = 400 WHERE id = 3;

alter table T_INTERVAL enable row movement;
UPDATE T_INTERVAL SET Salary = 100002 WHERE id = '14-APR-2023';

alter table T_HASH enable row movement;
UPDATE T_HASH SET name = 'NewName' WHERE id = 1;

alter table T_LIST enable row movement;
UPDATE T_LIST SET NAME = 'John' WHERE id = 4;

ALTER TABLE T_RANGE MERGE PARTITIONS P1, P2 INTO PARTITION P2;

SELECT partition_name, high_value
FROM user_tab_partitions
WHERE table_name = 'T_RANGE';

ALTER TABLE T_RANGE SPLIT PARTITION p2 INTO (
  PARTITION p1 VALUES LESS THAN (5000),
  PARTITION p2
);

Drop TABLE T_EXCHANGE;

CREATE TABLE T_EXCHANGE
(
   ID NUMBER,
   NAME VARCHAR2(50),
   SALARY NUMBER
);

INSERT INTO T_EXCHANGE VALUES (1, 'Exchange row 1', 2222);
INSERT INTO T_EXCHANGE VALUES (2, 'Exchange row 2', 3333);
INSERT INTO T_EXCHANGE VALUES (3, 'Exchange row 3', 4444);

ALTER TABLE T_RANGE EXCHANGE PARTITION FOR (1) WITH TABLE T_EXCHANGE;
SELECT * FROM T_RANGE;

SELECT table_name, partitioning_type
FROM user_part_tables;

SELECT partition_name
FROM user_tab_partitions
WHERE table_name = 'T_HASH';

SELECT *
FROM T_HASH PARTITION (SYS_P248);

SELECT *
FROM T_LIST PARTITION(P2);

