ALTER PLUGGABLE DATABASE XE_PDB
  OPEN READ WRITE FORCE;

CREATE GLOBAL TEMPORARY TABLE TEMPTB(
  S1 NUMBER(4) PRIMARY KEY
);

INSERT INTO TEMPTB(S1) VALUES (1234);

--3
CREATE SEQUENCE S1 START WITH 1000 INCREMENT BY 10 NOMINVALUE NOMAXVALUE NOCACHE NOCYCLE;

SELECT S1.NEXTVAL FROM DUAL;

CREATE SEQUENCE S2 START WITH 10 INCREMENT BY 10 MAXVALUE 100 NOCYCLE;

SELECT S2.NEXTVAL FROM dual;
SELECT S2.NEXTVAL FROM dual;
SELECT S2.NEXTVAL FROM dual;
SELECT S2.NEXTVAL FROM dual;
SELECT S2.NEXTVAL FROM dual;
SELECT S2.NEXTVAL FROM dual;
SELECT S2.NEXTVAL FROM dual;

CREATE SEQUENCE S3 START WITH 10 INCREMENT BY -10 MINVALUE -100 MAXVALUE 10 NOCYCLE ORDER;

SELECT S3.NEXTVAL FROM dual;
SELECT S3.NEXTVAL FROM dual;
SELECT S3.NEXTVAL FROM dual;
SELECT S3.NEXTVAL FROM dual;
SELECT S3.NEXTVAL FROM dual;
SELECT S3.NEXTVAL FROM dual;
SELECT S3.NEXTVAL FROM dual;

drop sequence s4;
CREATE SEQUENCE S4 START WITH 8 INCREMENT BY 1 MINVALUE 8 MAXVALUE 10 CYCLE CACHE 2 NOORDER;

SELECT S4.NEXTVAL FROM dual;
SELECT S4.NEXTVAL FROM dual;
SELECT S4.NEXTVAL FROM dual;
SELECT S4.NEXTVAL FROM dual;
SELECT S4.NEXTVAL FROM dual;
SELECT S4.NEXTVAL FROM dual;
SELECT S4.NEXTVAL FROM dual;

SELECT sequence_name FROM all_sequences WHERE sequence_owner = 'sys';

CREATE TABLE T1 (
  N1 NUMBER(20),
  N2 NUMBER(20),
  N3 NUMBER(20),
  N4 NUMBER(20)
)
CACHE
STORAGE (BUFFER_POOL KEEP);

ALTER SEQUENCE S3 MINVALUE -1000;
ALTER SEQUENCE S2 MAXVALUE 1000;
INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);
INSERT INTO T1 VALUES (S1.NEXTVAL, S2.NEXTVAL, S3.NEXTVAL, S4.NEXTVAL);

--9

CREATE CLUSTER ABC (
  X NUMBER(10),
  V VARCHAR2(12)
) HASHKEYS 200;

CREATE TABLE A (
  XA NUMBER(10),
  VA VARCHAR2(12),
  OTHER_COLUMN NUMBER(20))
  CLUSTER ABC(XA,VA);

CREATE TABLE B (
  XB NUMBER(10),
  VB VARCHAR2(12),
  COLUMN1 VARCHAR2(20))
  CLUSTER ABC(XB, VB);

CREATE TABLE C (
  XC NUMBER(10),
  VC VARCHAR2(12),
  COLUMN1 VARCHAR2(20))
  CLUSTER ABC(XC, VC);

SELECT table_name, cluster_name
FROM user_tables
WHERE cluster_name = 'ABC';

--14
drop synonym C_PRIVATE;
CREATE SYNONYM C_PRIVATE FOR C;

SELECT * FROM C_PRIVATE;

CREATE PUBLIC SYNONYM B_PUBLIC FOR B;

SELECT * FROM B_PUBLIC;

CREATE TABLE A1 (
  ID NUMBER(10) PRIMARY KEY,
  NAME VARCHAR2(20)
);

CREATE TABLE B1 (
  ID NUMBER(10) primary key,
  A_ID NUMBER(10),
  DATA VARCHAR2(20),
  CONSTRAINT fk_a_id FOREIGN KEY (A_ID) REFERENCES A1(ID)
);
drop table  b1;

INSERT INTO A1 VALUES (1, 'A1');
INSERT INTO A1 VALUES (2, 'A2');
INSERT INTO B1 VALUES (1, 1, 'B1');
INSERT INTO B1 VALUES (2, 1, 'B2');
INSERT INTO B1 VALUES (3, 2, 'B3');

CREATE VIEW V1 AS
SELECT A1.ID, A1.NAME, B1.DATA
FROM A1
INNER JOIN B1 ON A1.ID = B1.A_ID;

SELECT * FROM V1;

CREATE MATERIALIZED VIEW MV_TDV
build immediate
REFRESH complete
AS
SELECT A1.ID, A1.NAME, B1.DATA
FROM A1
INNER JOIN B1 ON A1.ID = B1.A_ID;

SELECT * FROM MV_TDV;

CREATE DATABASE LINK XE CONNECT TO system IDENTIFIED BY Dima22138 USING 'XE';
DROP DATABASE LINK XE;
SELECT * from V$TABLESPACE;

-- выполнение SELECT запроса на удаленной БД
SELECT * FROM V$TABLESPACE@XE;
--
-- -- выполнение INSERT
-- INSERT INTO my_table@remote_db VALUES (1, 'Value 1');
--
-- -- выполнение UPDATE
-- UPDATE my_table@remote_db SET my_column = 'New value' WHERE id = 1;
--
-- -- выполнение DELETE
-- DELETE FROM my_table@remote_db WHERE id = 1;
--
-- -- вызов процедуры
-- EXECUTE remote_procedure@remote_db(param1, param2);
--
-- -- вызов функции
-- SELECT remote_function@remote_db(param1, param2) FROM dual;