SELECT TABLESPACE_NAME FROM SYS.DBA_TABLESPACES;

CREATE TABLESPACE TDV_QDATA
DATAFILE 'D:\Oracle-db\LABS\TDV_QDATA.DBF'
SIZE 10M
OFFLINE;

ALTER TABLESPACE TDV_QDATA ONLINE;

ALTER USER TDV QUOTA 2M ON TDV_QDATA;

ALTER USER TDV DEFAULT TABLESPACE TDV_QDATA;

CREATE TABLE TDV_T1(
  C1 INTEGER PRIMARY KEY,
  C2 INTEGER
);

INSERT INTO TDV_T1 VALUES (1,1);
INSERT INTO TDV_T1 VALUES (2,2);
INSERT INTO TDV_T1 VALUES (3,3);

SELECT segment_name, TABLESPACE_NAME, bytes/1024/1024 MB FROM SYS.DBA_SEGMENTS WHERE TABLESPACE_NAME = 'TDV_QDATA';

ALTER TABLE TDV_T1 STORAGE (INITIAL 128K NEXT 128K);

DROP TABLE TDV_T1;

SELECT * FROM dba_RECYCLEBIN;

FLASHBACK TABLE TDV_T1 TO BEFORE DROP;

DECLARE
    X INTEGER;
BEGIN
    X:=4;
    WHILE X<10000
        LOOP
            INSERT INTO TDV_T1 VALUES (X, X);
            X:= X + 1;
        end loop;
end;

SELECT * FROM TDV_T1;

SELECT * FROM DBA_EXTENTS WHERE SEGMENT_NAME='TDV_T1';

SELECT ROWID FROM TDV_T1;
SELECT ORA_ROWSCN FROM TDV_T1;