SELECT tablespace_name
FROM dba_tablespaces;

SELECT file_name, tablespace_name
FROM dba_data_files;

ALTER SYSTEM SWITCH LOGFILE;

SELECT group#, status, FIRST_CHANGE#, bytes/1024/1024 AS size_mb
FROM v$log;

-- SELECT thread#, MAX(sequence#) AS last_seq
-- FROM v$log_history
-- GROUP BY thread#;

--4
SELECT member, group# FROM v$logfile;

ALTER DATABASE ADD LOGFILE GROUP 4 ('D:\Oracle-db\oradata\XE\REDO04.log') SIZE 10M;

ALTER DATABASE DROP LOGFILE GROUP 4;

SELECT log_mode FROM v$database;

SELECT MAX(sequence#) FROM v$archived_log;

--10
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

ALTER SYSTEM SWITCH LOGFILE;
SELECT * FROM V_$ARCHIVED_LOG;

ALTER SYSTEM ARCHIVE LOG ALL;
SELECT * FROM v$archived_log WHERE name LIKE '%/archivelog/%';

ALTER SYSTEM ARCHIVE LOG CURRENT;

SELECT NAME FROM V$ARCHIVED_LOG ORDER BY FIRST_TIME DESC;

SELECT DEST_ID, NAME FROM V$ARCHIVED_LOG ORDER BY FIRST_TIME DESC;

SELECT SEQUENCE#, FIRST_CHANGE#, NEXT_CHANGE#, NAME FROM V$ARCHIVED_LOG ORDER BY SEQUENCE#;


SELECT NAME FROM V$CONTROLFILE;

CREATE PFILE = 'P1.ORA' FROM SPFILE;

--ALTER DATABASE BACKUP CONTROLFILE TO TRACE;

--SELECT * FROM v$parameter WHERE name LIKE '%control_files%';
