CREATE TABLE XXX_tTHAK47 (FIRSST NUMBER(3) PRIMARY KEY, SECCOND VARCHAR2(50));
INSERT INTO XXX_tTHAK47(FIRSST, SECCOND) VALUES (122, '23ASAS');
INSERT INTO XXX_tTHAK47(FIRSST, SECCOND) VALUES (133, '3F4DF3');
INSERT INTO XXX_tTHAK47(FIRSST, SECCOND) VALUES (145, '8DFD232');
COMMIT;
UPDATE XXX_TTHAK47 SET SECCOND = 'DELEET' WHERE SECCOND = '23ASAS' OR FIRSST = 145;
COMMIT;
SELECT FIRSST, SECCOND FROM XXX_TTHAK47 WHERE FIRSST = 122;
SELECT SUM(FIRSST) FROM XXX_TTHAK47 WHERE SECCOND = 'DELEET';
DELETE XXX_TTHAK47 WHERE FIRSST = 122;
ROLLBACK;
SELECT FIRSST, SECCOND FROM XXX_TTHAK47 WHERE FIRSST = 122;

CREATE TABLE XXX_TTHAK47_CHILD (CHIL NUMBER(3), CONSTRAINT FK_CHIL FOREIGN KEY(CHIL) REFERENCES XXX_TTHAK47(FIRSST));

INSERT INTO XXX_TTHAK47_CHILD VALUES (122);
SELECT XXX_TTHAK47.SECCOND FROM XXX_TTHAK47_CHILD INNER JOIN XXX_TTHAK47 ON XXX_TTHAK47_CHILD.CHIL = XXX_TTHAK47.FIRSST;
SELECT XXX_TTHAK47.SECCOND, XXX_TTHAK47.FIRSST FROM XXX_TTHAK47_CHILD FULL OUTER JOIN XXX_TTHAK47 ON XXX_TTHAK47_CHILD.CHIL = XXX_TTHAK47.FIRSST;
COMMIT;
DROP TABLE XXX_TTHAK47_CHILD;
DROP TABLE XXX_TTHAK47;
