USE UNIVER;

SELECT MAX(AUDITORIUM.AUDITORIUM_CAPACITY)[люйяхлюкэмюъ блеярхлнярэ],
		MIN(AUDITORIUM.AUDITORIUM_CAPACITY)[лхмхлюкэмюъ блеярхлнярэ],
		AVG(AUDITORIUM.AUDITORIUM_CAPACITY)[япедмъъ блеярхлнярэ],
		SUM(AUDITORIUM.AUDITORIUM_CAPACITY)[яслюпмюъ блеярхлнярэ],
		COUNT(AUDITORIUM.AUDITORIUM)[йнк-бн юсдхрнпхи]
	FROM AUDITORIUM;

SELECT AUDITORIUM_TYPE.AUDITORIUM_TYPENAME,
		MAX(AUDITORIUM.AUDITORIUM_CAPACITY)[люйяхлюкэмюъ блеярхлнярэ],
		MIN(AUDITORIUM.AUDITORIUM_CAPACITY)[лхмхлюкэмюъ блеярхлнярэ],
		AVG(AUDITORIUM.AUDITORIUM_CAPACITY)[япедмъъ блеярхлнярэ],
		SUM(AUDITORIUM.AUDITORIUM_CAPACITY)[яслюпмюъ блеярхлнярэ],
		COUNT(AUDITORIUM.AUDITORIUM)[йнк-бн юсдхрнпхи]
		FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
		ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
									GROUP BY AUDITORIUM_TYPE.AUDITORIUM_TYPENAME

SELECT *
	FROM (SELECT CASE WHEN PROGRESS.NOTE = 10 THEN '10'
					WHEN PROGRESS.NOTE BETWEEN 8 AND 9 THEN '8-9'
					WHEN PROGRESS.NOTE BETWEEN 6 AND 7 THEN '6-7'
					ELSE '4-5'
					END [нжемйю], COUNT(*)[йнк-бн]
	FROM PROGRESS GROUP BY CASE
					WHEN PROGRESS.NOTE = 10 THEN '10'
					WHEN PROGRESS.NOTE BETWEEN 8 AND 9 THEN '8-9'
					WHEN PROGRESS.NOTE BETWEEN 6 AND 7 THEN '6-7'
					ELSE '4-5'
					END) AS T
							ORDER BY CASE [нжемйю]
								WHEN '10' THEN 1
								WHEN '8-9' THEN 2
								WHEN '6-7' THEN 3
								WHEN '4-5' THEN 4
								ELSE 0
								END

SELECT FACULTY.FACULTY, GROUPS.PROFESSION, STUDENT.IDGROUP, ROUND(AVG(CAST(PROGRESS.NOTE AS float(4))),2)[япедмъъ нжемйю] 
		FROM FACULTY INNER JOIN GROUPS
		ON FACULTY.FACULTY = GROUPS.FACULTY
		INNER JOIN STUDENT
		ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS
		ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
		WHERE PROGRESS.SUBJECT = 'нюХо' OR PROGRESS.SUBJECT = 'ад'
		GROUP BY FACULTY.FACULTY,
				GROUPS.PROFESSION,
				STUDENT.IDGROUP

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE)[япедмхе нжемйх]
		FROM FACULTY INNER JOIN GROUPS
		ON FACULTY.FACULTY = GROUPS.FACULTY
		INNER JOIN STUDENT
		ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS
		ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		WHERE FACULTY.FACULTY = 'рнб'
		GROUP BY ROLLUP(FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT)

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE)[япедмхе нжемйх]
		FROM FACULTY INNER JOIN GROUPS
		ON FACULTY.FACULTY = GROUPS.FACULTY
		INNER JOIN STUDENT
		ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS
		ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		WHERE FACULTY.FACULTY = 'рнб'
		GROUP BY CUBE(FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT)

SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE)[япедмхе нжемйх]
		FROM GROUPS INNER JOIN STUDENT
		ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS
		ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		WHERE GROUPS.FACULTY = 'рнб'
		GROUP BY ROLLUP(GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT)
	UNION
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE)[япедмхе нжемйх]
		FROM GROUPS INNER JOIN STUDENT
		ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS
		ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		WHERE GROUPS.FACULTY = 'урХр'
		GROUP BY ROLLUP(GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT)

INTERSECT(SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE)[япедмхе нжемйх]
		FROM GROUPS INNER JOIN STUDENT
		ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS
		ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		WHERE GROUPS.FACULTY = 'рнб'
		GROUP BY ROLLUP(GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT)
	UNION
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE)[япедмхе нжемйх]
		FROM GROUPS INNER JOIN STUDENT
		ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS
		ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		WHERE GROUPS.FACULTY = 'урХр'
		GROUP BY ROLLUP(GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT))

EXCEPT(SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE)[япедмхе нжемйх]
		FROM GROUPS INNER JOIN STUDENT
		ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS
		ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		WHERE GROUPS.FACULTY = 'рнб'
		GROUP BY ROLLUP(GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT)
	UNION
SELECT GROUPS.PROFESSION, PROGRESS.SUBJECT, AVG(PROGRESS.NOTE)[япедмхе нжемйх]
		FROM GROUPS INNER JOIN STUDENT
		ON GROUPS.IDGROUP = STUDENT.IDGROUP
		INNER JOIN PROGRESS
		ON PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
		WHERE GROUPS.FACULTY = 'урХр'
		GROUP BY ROLLUP(GROUPS.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT))

SELECT PROGRESS.SUBJECT, PROGRESS.NOTE, 
	(SELECT COUNT(*) FROM PROGRESS P2
		WHERE P2.IDSTUDENT = PROGRESS.IDSTUDENT
			AND P2.SUBJECT = PROGRESS.SUBJECT)[йнкбн]
	FROM PROGRESS
	GROUP BY PROGRESS.NOTE, PROGRESS.SUBJECT, PROGRESS.IDSTUDENT
	HAVING PROGRESS.NOTE BETWEEN 8 AND 9