USE UNIVER;

SELECT FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME
	FROM FACULTY, PULPIT
	WHERE FACULTY.FACULTY = PULPIT.FACULTY  
		AND
		PULPIT.FACULTY IN (SELECT PROFESSION.FACULTY
							FROM PROFESSION
							WHERE (PROFESSION_NAME LIKE '%технологии%' or PROFESSION_NAME LIKE '%технологий%'))

SELECT FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME
	FROM FACULTY INNER JOIN PULPIT
	ON FACULTY.FACULTY = PULPIT.FACULTY  
		AND
		PULPIT.FACULTY IN (SELECT PROFESSION.FACULTY
							FROM PROFESSION
							WHERE (PROFESSION_NAME LIKE '%технологии%' or PROFESSION_NAME LIKE '%технологий%'))

SELECT FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME
	FROM FACULTY INNER JOIN PULPIT
	ON FACULTY.FACULTY = PULPIT.FACULTY  
		INNER JOIN PROFESSION
					ON PROFESSION.FACULTY = PULPIT.FACULTY WHERE(PROFESSION_NAME LIKE '%технологии%' or PROFESSION_NAME LIKE '%технологий%')

SELECT AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM.AUDITORIUM_CAPACITY, AUDITORIUM.AUDITORIUM_NAME
		FROM AUDITORIUM
			WHERE AUDITORIUM.AUDITORIUM_CAPACITY = (SELECT TOP(1) AUDITORIUM.AUDITORIUM_CAPACITY
																FROM AUDITORIUM
																ORDER BY AUDITORIUM_CAPACITY DESC)

SELECT FACULTY.FACULTY_NAME
	FROM FACULTY
	WHERE NOT EXISTS (SELECT PULPIT.FACULTY FROM PULPIT
								WHERE PULPIT.FACULTY = FACULTY.FACULTY)

SELECT TOP(1)
	(SELECT AVG(NOTE) FROM PROGRESS
					WHERE PROGRESS.SUBJECT LIKE 'ОАиП')[ОАИП],
	(SELECT AVG(NOTE) FROM PROGRESS
					WHERE PROGRESS.SUBJECT LIKE 'БД')[БД],
	(SELECT AVG(NOTE) FROM PROGRESS
					WHERE PROGRESS.SUBJECT LIKE 'СУБД')[СУБД]
	FROM PROGRESS

SELECT AUDITORIUM.AUDITORIUM_CAPACITY
		FROM AUDITORIUM
		WHERE AUDITORIUM_CAPACITY >=ALL (SELECT AUDITORIUM_CAPACITY 
													FROM AUDITORIUM
													WHERE AUDITORIUM_NAME LIKE '%ЛБ-К%')

SELECT AUDITORIUM.AUDITORIUM_CAPACITY
		FROM AUDITORIUM
		WHERE AUDITORIUM_CAPACITY >=ANY (SELECT AUDITORIUM_CAPACITY 
													FROM AUDITORIUM
													WHERE AUDITORIUM_NAME LIKE '%ЛБ-К%')

