USE UNIVER;

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
		FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
		ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
		FROM AUDITORIUM INNER JOIN AUDITORIUM_TYPE
		ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
				AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%Компьютер%'

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
		FROM AUDITORIUM, AUDITORIUM_TYPE
		WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
		FROM AUDITORIUM, AUDITORIUM_TYPE
		WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
				AND AUDITORIUM_TYPE.AUDITORIUM_TYPENAME LIKE '%Компьютер%'

SELECT FACULTY.FACULTY, PULPIT.PULPIT, PROFESSION.PROFESSION, SUBJECT.SUBJECT_NAME, STUDENT.NAME, PROGRESS.NOTE,
		CASE 
		WHEN (PROGRESS.NOTE BETWEEN 6 AND 6) THEN 'шесть'
		WHEN (PROGRESS.NOTE BETWEEN 7 AND 7) THEN 'семь'
		WHEN (PROGRESS.NOTE BETWEEN 8 AND 8) THEN 'восемь'
		ELSE ''
		end [Оценка]
		FROM FACULTY INNER JOIN PULPIT
			ON FACULTY.FACULTY = PULPIT.FACULTY
		JOIN SUBJECT
			ON PULPIT.PULPIT = SUBJECT.PULPIT
		JOIN PROFESSION
			ON FACULTY.FACULTY = PROFESSION.FACULTY
		JOIN PROGRESS
			ON SUBJECT.SUBJECT = PROGRESS.SUBJECT
		JOIN STUDENT
			ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
								ORDER BY 
								PROGRESS.NOTE DESC;

SELECT FACULTY.FACULTY, PULPIT.PULPIT, PROFESSION.PROFESSION, SUBJECT.SUBJECT_NAME, STUDENT.NAME, PROGRESS.NOTE,
		CASE 
		WHEN (PROGRESS.NOTE BETWEEN 6 AND 6) THEN 'шесть'
		WHEN (PROGRESS.NOTE BETWEEN 7 AND 7) THEN 'семь'
		WHEN (PROGRESS.NOTE BETWEEN 8 AND 8) THEN 'восемь'
		ELSE ''
		end [Оценка]
		FROM FACULTY INNER JOIN PULPIT
			ON FACULTY.FACULTY = PULPIT.FACULTY
		JOIN SUBJECT
			ON PULPIT.PULPIT = SUBJECT.PULPIT
		JOIN PROFESSION
			ON FACULTY.FACULTY = PROFESSION.FACULTY
		JOIN PROGRESS
			ON SUBJECT.SUBJECT = PROGRESS.SUBJECT
		JOIN STUDENT
			ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT
								ORDER BY 
								(CASE 
									WHEN(PROGRESS.NOTE = 7) THEN 4
									WHEN(PROGRESS.NOTE = 8) THEN 3
									WHEN(PROGRESS.NOTE = 6) THEN 2
									ELSE 1
								END) DESC;

SELECT PULPIT.PULPIT_NAME, ISNULL(TEACHER.TEACHER_NAME, '***')[ПРЕПОДАВАТЕЛИ]
		FROM PULPIT LEFT OUTER JOIN TEACHER
			ON PULPIT.PULPIT = TEACHER.PULPIT;

SELECT ISNULL(TEACHER.TEACHER_NAME, '***')[ПРЕПОДАВАТЕЛИ], PULPIT.PULPIT_NAME
		FROM TEACHER RIGHT OUTER JOIN PULPIT
			ON PULPIT.PULPIT = TEACHER.PULPIT;

SELECT AUDITORIUM.AUDITORIUM_TYPE, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME
		FROM AUDITORIUM FULL OUTER JOIN AUDITORIUM_TYPE
			ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE

SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM_TYPE.AUDITORIUM_TYPENAME 
		FROM AUDITORIUM CROSS JOIN AUDITORIUM_TYPE
		WHERE AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE